# Site settings
title: 第8哥小灶时间
email: sublimepython@gmail.com
description: Keep going...
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  de8ug
# permalink: /:year/:month/:day/:title/
permalink: /:year/:month/:day/:id/

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "page:num"

# add sitemap
plugins: 
  - jekyll-sitemap

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
