# Jekyll configuration

name: 咆哮金刚猪的编程乐园
description: 不把github鼓捣成博客的程序猿不是一个好的喵星人

# Url is currently only used only for the RSS feed in feed.xml
url: http://howiewang.github.io
#url: http://localhost:4000

avatar: https://avatars2.githubusercontent.com/u/5234979?v=3&s=460

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
#baseurl: '/jekyll-clean-dark'

social:
  github: howiewang

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrika:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: Howie
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
